print("Modules")
print("Internal Modules also called built in modules")
print("External Modules also called manually installed modules")
print("To install external modules we use pip")
print("Command to install pip is")
print("pip install module_name")
print("Installing modules in linux or mac is")
print("pip3 install module_name")
print("import module_name to use the module in your code")
print("pip install --upgrade pip or module_name to upgrade pip or module")
print("pip uninstall module_name to uninstall the module")
print("pip install scikit-learn to install scikit-learn module")
print("pip install --upgrade scikit-learn to upgrade scikit-learn module")
print("sklearn is for machine learning")
print("pandas is for data analysis")
print("module are code libaries which are pre written and we can use them in our code")
print("built in modules in python")
import hashlib
